.\" Manpage for textgames
.\" Report errors or typos to https://github.com/CrackedMatter/textgames
.TH textgames 6 "16 July 2021" "1.2.0" "textgames man page"

.SH NAME
textgames \- engine for text-based games

.SH SYNOPSIS
.B textgames
[\fIFILE\fR]...

.SH DESCRIPTION
An interpreter/engine for text-based games (you don't necessarily have to use it for games though) written in bash.

.\" .SH OPTIONS

.SH SEE ALSO
\fBtxget(6)\fR, \fBtxgc(6)\fR

.SH LINKS
.UR https://crackedmatter.github.io/
\fBWebsite\fR
.UE

.UR https://github.com/CrackedMatter/textgames
\fBRepository\fR
.UE

.SH BUGS
As of 16 July 2021 there are no known bugs.
Please report issues on the
.UR https://github.com/CrackedMatter/issues
issue tracker
.UE .

.SH AUTHOR
.UR https://github.com/CrackedMatter
.UE
